CIRCUITPY_WIFI_SSID="CEGEP IdO"
CIRCUITPY_WIFI_PASSWORD="!nt$l??!g$nt*"

SITEWEB_GITHUB_LEARN=https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/
ADAFRUIT_OVERVIEW=https://io.adafruit.com/RyanBadye/overview
AIO_USERNAME="RyanBadye"
AIO_KEY="aio_JXLS26mGJGJUHp5mE1AmJKBQ040W"
export_IO_USERNAME=RyanBadye
export_IO_KEY=aio_JXLS26mGJGJUHp5mE1AmJKBQ040W
ADAFRUIT_IO_USERNAME=RyanBadye
ADAFRUIT_IO_KEY=aio_JXLS26mGJGJUHp5mE1AmJKBQ040W


WEB_ADAFRUIT_PERSONNEL=RyanBadye
WEB_ADAFRUIT.COM=https://io.adafruit.com/RyanBadye/feeds
FEED=temperature
FEED=humidite
FEED=connexionweb
