name: Deploy to Azure VM

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: adminweb
          server: 4.239.253.190
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.AZURE_VM_KEY }}

          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www/html

          # sftp args
          args: '-o ConnectTimeout=5'

