# .github/workflows/deploy-sftp.yml
name: Deploy via SFTP

on:
  push:
    branches:
      - main # Déclenche le déploiement quand tu pushes sur main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer l’outil lftp (SFTP client)
      #- name: Install lftp
       # run: sudo apt-get update && sudo apt-get install -y lftp

      # 3️⃣ Configurer la clé SSH
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.UBUNTU_WEB_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      # 4️⃣ Optionnel : ajouter le serveur aux known_hosts
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.IP_UBUNTU }} >> ~/.ssh/known_hosts
        shell: bash

      # 5️⃣ Déployer via SFTP
      - name: Deploy files via SFTP
        run: |
          lftp -u "${{ secrets.USER_SFTP }}","" sftp://[${{ secrets.IP_UBUNTU }}]:${{ secrets.PORT_SSH }} <<EOF
          set sftp:auto-confirm yes
          mirror -R --verbose --continue --parallel=2 ./ /delifruit
          quit
          EOF
        shell: bash
