name: Deploy to Azure VM

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer rsync (pour copier les fichiers rapidement)
      #- name: Install rsync
        #run: |
          #sudo apt-get update
         # sudo apt-get update && sudo apt-get install -y rsync
          
      #- name: Fix rsync dependency
        #run: |
          #sudo apt-get install -y rsync libacl1

      # 3️⃣ Setup de la clé SSH depuis le secret GitHub
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_VM_KEY }}" > ./azure_vm_key.pem
          chmod 600 ./azure_vm_key.pem

      # 4️⃣ Ajouter l’hôte de la VM à known_hosts
      - name: Add Azure VM to known_hosts
        run: 
          ssh-keyscan -H 4.239.253.190 >> ~/.ssh/known_hosts

      # 5️⃣ Copier les fichiers du dépôt vers le serveur Apache
      - name: Deploy website to Apache
        run: |
          rsync -avz -e "ssh -i ./azure_vm_key.pem" ./ adminweb@4.239.253.190:/var/www/html/
      # rsync -avz -e "ssh -i ./azure_vm_key.pem" ./ AOJBRBKDB@4.239.253.190:/var/www/html/

